volumes:
  data:


services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=user
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
